version: 2

defaults: &defaults
  working_directory: ~/rta
  docker:
    - image: circleci/node:10

cypress: &cypress
  working_directory: ~/rta
  docker:
    # the Docker image with Cypress dependencies
    - image: cypress/base:6
      environment:
        ## this enables colors in the output
        TERM: xterm

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/rta
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          key: v2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths: .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/rta
      - run: yarn run lint
  flow:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/rta
      - run: yarn run flow:check
  e2e:
    <<: *cypress
    steps:
      - attach_workspace:
          at: ~/rta
      - run: yarn run cypress
  tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/rta
      - restore_cache:
          keys:
            - v2-jest-cache-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-jest-cache-
      - run: yarn run test
      - save_cache:
          key: v2-jest-cache-{{ checksum "yarn.lock" }}
          paths:
            - .jestCache
      - persist_to_workspace:
          root: .
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/rta
      - run: yarn run build
      - persist_to_workspace:
          root: .
          paths: .
  build-example:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/rta
      - run: yarn run dev:build && bash .circleci/comment-artifacts.sh
      - store_artifacts:
          path: ./example-build
          destination: example

workflows:
  version: 2
  build:
    jobs:
      - install-dependencies
      - lint:
          requires:
            - install-dependencies
      - flow:
          requires:
            - install-dependencies
      - tests:
          requires:
            - install-dependencies
      - e2e:
          requires:
            - install-dependencies
            - tests
      - build:
          requires:
            - tests
            - e2e
      - build-example:
          requires:
            - tests
            - e2e
